cache:
    - "c:\\sr -> appveyor.yml"

install:
    - ps: Start-FileDownload 'http://www.stackage.org/stack/windows-i386' -FileName stack.zip
    - ps: Start-FileDownload 'http://www.eecs.berkeley.edu/~alanmi/abc/abc10216.exe' -FileName abc.exe

build: off

before_test:
    - dir
    - 7z x stack.zip stack.exe
    - set "PATH=%PATH%;%cd%"

clone_folder: "c:\\project\\scenco"
environment:
  global:
    STACK_ROOT: "c:\\sr"

test_script:
    - stack init
    - stack setup > nul
    - stack exec -- ghc --version
    - stack build
    - stack test
